apiVersion: apps/v1
kind: Deployment
metadata:
  name: clazz-app-deployment
spec:
  replicas: 3  # 애플리케이션의 복제본 수
  selector:
    matchLabels:
      app: clazz-app  # 레이블을 수정
  template:
    metadata:
      labels:
        app: clazz-app  # 레이블을 수정
    spec:
      containers:
        - name: clazz-app-container  # 컨테이너 이름 수정
          image: clazz.kr.ncr.ntruss.com/clazz-app:latest  # 배포할 도커 이미지
          ports:
            - containerPort: 8080  # 애플리케이션의 포트
---
apiVersion: v1
kind: Service
metadata:
  name: clazz-app-service  # 서비스 이름 수정
spec:
  selector:
    app: clazz-app  # 레이블을 수정
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # 컨테이너의 포트와 매핑
  type: LoadBalancer  # 외부 접근이 필요한 경우